/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#505f76",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "primary-fixed": "#c9e6ff",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "inverse-primary": "#89ceff",
        "on-tertiary-fixed": "#001d31",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary": "#006591",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "outline": "#6e7881",
        "surface-container": "#eceef0",
        "on-primary-container": "#003751",
        "on-tertiary-fixed-variant": "#004b73",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-tint": "#006591",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3e4850",
        "on-secondary-fixed": "#0b1c30",
        "on-background": "#191c1e",
        "on-primary-fixed": "#001e2f",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004c6e",
        "outline-variant": "#bec8d2",
        "tertiary-fixed": "#cce5ff",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#40a2e7",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#0ea5e9",
        "tertiary": "#006398",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-surface": "#2d3133",
        "surface": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#003655",
        "primary-fixed-dim": "#89ceff",
        "error": "#ba1a1a",
        "secondary-container": "#d0e1fb",
        "tertiary-fixed-dim": "#93ccff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin": "2rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["18px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
